### ISSUE TITLE
Ability Cooldowns

### ISSUE THREAD

**Issue by KevTG** [MCreator-Examples/Feedback#1]
can you make a tutorial on how to make a weapon trigger procedure cooldown?

Example: 

I have made a sword in Mcreator with a lightning strike ability. Right now i have a randomizer to make it 5% chance to trigger the ability when a living entity is hit, but i would much rather have so i can use the ability when i want to, and have a 2 minute cooldown before i can use it again, but i dont know how to make that:)

**Comment by northwesttreesgaming** [comment]
![image](https://user-images.githubusercontent.com/47284617/118168169-685c7980-b3dc-11eb-9d04-e3658f41f300.png)

I have covered how to make timers using global variables however it is also to do the same mechanics with any NBT variables as well. Items have NBT variables so you only need to make a simple item NBT timer for the item tick update, test if the value is greater than 0 if there then count down to 0. 

When the tool is used you need to set the timer as seen in the procedure below the first one.

You should also test if the timer is = to 0 to be able to use the timer.

I don't see the need right now to update the tutorial as the concept from my past tutorials regarding timers still works fine except for not including that NBT variables do work fine for timers as well. You can use a player side global timer as well if you don't want the item to update from the NBT data just make sure to test for the global variable instead.

I will add the suggestion to the video update section for the project.

**Comment by northwesttreesgaming** [comment]
Published
[https://youtu.be/gTbWiMu-M-0](https://youtu.be/gTbWiMu-M-0)
