### ISSUE TITLE
Config file tutorial

### ISSUE THREAD

**Issue by TotalBlacksmith** [MCreator-Examples/Feedback#11]
A customizable file in which you can allow people to alter features to your mod conveniently and quickly.

Feature #1 The ability to select individual elements and allow certain values associated with said elements to be altered in the config file.

Feature #2 N/A

Feature #3 N/A

**Comment by northwesttreesgaming** [comment]
At the moment this is not possible from a document, however, I can do a tutorial on game rules as this is a similar system for world configuration, and is really dynamic in procedures.

**Comment by Goldorion** [comment]
I made two workspace examples using my File manager plugins. You can both find them on the plugin's page of File Manager. I also talked with NWT, so he will suggest a tutorial for making custom configuration files in the next PickIT. https://mcreator.net/plugin/64638/file-creator
