### ISSUE TITLE
[Progress bar] <Expanded tutorial on progress bar>

### ISSUE THREAD

**Issue by bdaly3412** [MCreator-Examples/Feedback#12]
## DESCRIPTION (Required)
>1.  To help me and other people alike stuck on the progress bar
>1.  Show us in depth how to create a progress bar and maybe a github link.

## LIST OF KEY FEATURES (Required)
> Describe any new features you want to be added.

* [x] custom times on the progress bar
* [ ] Feature 2
* [ ] Feature 3 . . .

## ADDITIONAL CONTEXT (Optional)
> Add any other context or screenshots about the feature request here.

**Comment by northwesttreesgaming** [comment]
I have made a tutorial on progress bars for 2020.5 it should still work in 2021.1.

I don't seem to have the download on google drive or on GitHub so I will work on putting a page together for that tutorial soon as I can.
