### ISSUE TITLE
Locating Substring Position

### ISSUE THREAD

**Issue by BigMartin58** [MCreator-Examples/Feedback#143]
I believe it would be useful to do a tutorial on locating the position of a substring.

Here is my youtube comment for reference:

> Is it possible to get the location of a substring within text in order to replace or trim a substring dynamically? For example, I send a message of "Get block at X Y Z" but trim/replace the registry.
So, "Get block at X Y Z" = "minecraft:oak_planks", but trimmed = "oak_planks" OR "mekanism:energy_cube" = "energy_cube".
It seems possible, but I'm having trouble figuring out the method.

I don't know how to label as tutorial request.

**Comment by northwesttreesgaming** [comment]
I will work on that when I have what I have in the works done.

**Comment by northwesttreesgaming** [comment]
The tutorial will be posted here.
https://youtu.be/hDgzMacOXHs
