### ISSUE TITLE
Fluid Storage Tutorial

### ISSUE THREAD

**Issue by TheOnlyGalaxyGaming** [MCreator-Examples/Feedback#15]
I want to make a tank to store either water or lava using the fluid storage feature in mcreator

in terms of what should be covered, i think a basic explanation of how fluid blocks work, and how to do simple thing with it, such as a tank that holds say 8000 mb of water

Features
Water tank
the procedure required
how to make the gui and such

if you're reading this, thanks for your time

**Comment by northwesttreesgaming** [comment]
I have not used this feature yet. I have used forge energy in the past however it's a bit unreliable, to say the least.
I will try to figure it out though in my spare time, thank you for your suggestion.

**Comment by northwesttreesgaming** [comment]
Completed
[https://youtu.be/4CzXt1YFeOM](https://youtu.be/4CzXt1YFeOM)
