### ISSUE TITLE
Custom Spawn Eggs

### ISSUE THREAD

**Issue by Herobrine7707** [MCreator-Examples/Feedback#154]
### Description

I need a tutorial for spawn eggs I'm trying to create a mod and have been trying to create a method for spawn eggs for a long time. First I tried right-clicking on creature position but then there was no animation and the mob always spawned at the same place place where the player is and then I have it with right cl

### Features and uses

1.a creatures spawn proceed on right click

2.a procedure when clicking on a mob with the mouse wheel

3. a delete procedure like spawn eggs if you only have one in your inventory

### Attachments

![Angry Animals   C__Users_fabia_MCreatorWorkspaces_angry_animals_  - SpawnAngryPigWennRechtsklickAufDemBlock (Prozedur) - MCreator 2023 1 EAP (04717) 20 02 2023 08_17_26](https://user-images.githubusercontent.com/87422017/220038027-dda42aae-5aa4-430d-bbc6-889e358bf4fe.png)

### Feature Request tracker rule checks (please read carefully)

- [X] I have checked NorthWestTrees Gaming YouTube Channel <a href='https://www.youtube.com/@NorthWestTreesGaming' target='_blank'> MCreator Playlists</a> and it has not been made yet.
- [X] I have checked MCE <a href='https://github.com/orgs/MCreator-Examples/projects/7/views/1?groupedBy%5BcolumnId%5D=Status' target='_blank'>Organaization Projects</a> and the idea has not been suggested yet.</a>

**Comment by northwesttreesgaming** [comment]
This should be possible through a right-click procedure for a block and getting the direction face of the such block then offsetting the coordinates for the entity to spawn after some basic testing if there is room for the entity to spawn eg air blocks. I am not sure when I will have time to work on this but I will add it to planned so I remember. Thanks for the suggestion <3

**Comment by northwesttreesgaming** [comment]
The video will be public in a week.
https://youtu.be/Wt4dgZ3eFgQ
