### ISSUE TITLE
Bounding box for larger models and .obj models

### ISSUE THREAD

**Issue by LordRelentless** [MCreator-Examples/Feedback#155]
### Description

Here's the problem I'm currently working on trying to figure out the bounding boxes for a larger (it's 12 blocks by 12 blocks a massive vault door like Fallout 4 style). The problem is, no matter how I work the bounding boxes, be it creating seperate boxes for each section of the model (each box being a standard box size) or one large bounding box, it doesn't make the entire model solid. I definitely need this to make it work like a proper protective door. I've tried everything and the max space I could get to work with the model is a 3x3 area. I've been working on this single model for 9 weeks now and I can't seem to get the bounding boxes to work. 

### Features and uses

Just an easier bounding box method, for example having say a master bounding box where you put in the coordinates for an entire model and then a checkbox option to autogenerate a subdivision of bounding boxes for the master box selected that is comprised of individual standards sized (16 x 16 x 16) bounding boxes that fill the space of the master bounding box. 

### Feature Request tracker rule checks (please read carefully)

- [X] I have checked NorthWestTrees Gaming YouTube Channel <a href='https://www.youtube.com/@NorthWestTreesGaming' target='_blank'> MCreator Playlists</a> and it has not been made yet.
- [X] I have checked MCE <a href='https://github.com/orgs/MCreator-Examples/projects/7/views/1?groupedBy%5BcolumnId%5D=Status' target='_blank'>Organaization Projects</a> and the idea has not been suggested yet.</a>

**Comment by northwesttreesgaming** [comment]
You need to use a multi-block system for things like this, using a large model that goes outside of the 1m cube eg 16 pixels will result in odd behaviour from the game. Minecraft uses multi-blocks for things like doors, beds and double flowers and is the better way to make models. I also have seen mods that use models outside have issues with shader packs so it's best to model each block and set the hitbox based on the model's minimum and maximum position points in the JSON file. Using this method will save you a lot of time setting up the bounding boxes and will always be correct for the hitbox values.

**Comment by LordRelentless** [comment]
Okay, well then how about a tutorial that addresses using multiblock in this fashion? I can't find any tutorials on this anywhere, and speaking to not only pro-modders for Minecraft and the various top level modders on MCreator Hub and other MCreator discords, as well as the Minecraft Modders Discord, nobody has an express tutorial on how to actually do multiblock; be it in MCreator nor straight via Java. Telling me I need to do X when there is no explanation of how to do X really doesn't address the  issue.
