### ISSUE TITLE
Entity Spawning Conditions

### ISSUE THREAD

**Issue by PixelGuy123** [MCreator-Examples/Feedback#38]
Description:
Advanced... I guess not advanced (that's only the name), I would like to have a tutorial where you show how to use Natural Entity Spawning Codition (and many examples of course).

Features:

1. How to use _natural entity spawning codition_
2. How to force entities to spawn in certain biomes (desert for example, creatures can't spawn on sand, and this is a little hard to solve).
3. Good Examples to give people ideas

**Comment by TheLimeSheep** [comment]
Yes, my entities won't spawn either, even on mycelium

**Comment by northwesttreesgaming** [comment]
Depending on the spawn type for the entity this is done using Minecraft tags these days.

All of these are under the Minecraft namespace for block tags.
They can be found on this page https://minecraft.wiki/w/Tag


| Tag | Blocks |
| --- | --- |
| animals_spawnable_on | grass_block |
| axolotls_spawnable_on | clay |
| foxes_spawnable_on | coarse_dirt, grass_block, podzol, snow, snow_block |
| frogs_spawnable_on | grass_block, mangrove_roots, mud, muddy_mangrove_roots |
| goats_spawnable_on | #animals_spawnable_on, gravel, snow, snow_block, stone, packed_ice |
| mooshrooms_spawnable_on | mycelium |
| parrots_spawnable_on | grass_block, air, #leaves, #logs |
| polar_bears_spawnable_on_alternate | ice |
| prevent_mob_spawning_inside | #rails |
| rabbits_spawnable_on | grass_block, snow, snow_block, sand |
| wolves_spawnable_on | grass_block, snow, snow_block |

Pretty sure that's all of them.
Most entities use animals like pigs, sheep, cows, and chickens, the other ones are self-explanatory.
If you set your animal spawn condition to animals then it will use that block tag.

Custom dimensions with different terrain types like new grass blocks will need to have the tag for the entity to spawn on them. Keep in mind that you control what entities spawn in custom biomes through your biome element so if you don't want pigs or sheep but only cows or custom mobs then this would be controlled through the biome, not the tag, the tag just allows them to spawn naturally when in the correct biome.

I also think monsters spawn differently there is no tag for them so most likely they don't have restrictions to natural generation.

**Comment by PixelGuy123** [comment]
Woah, I genuinely forgot about this issue and I'm glad you still replied to it, although I don't use MCreator (may come back though), that might be helpful in the future.

**Comment by northwesttreesgaming** [comment]
https://youtu.be/8BfnvFCz4VY
Will be released this week
