### ISSUE TITLE
Custom villager professions and and jobsite blocks

### ISSUE THREAD

**Issue by northwesttreesgaming** [MCreator-Examples/Feedback#81]
### Description

Basically, new villager entities use different types of entities and workplaces like Grindstones, Filters tables and such.

- Requires AAI or official support to be added.

### Features and uses

1. Work Blocks
2. Different styles of entities for each work block.
3. Sleeping mechanics
4. Gathering mechanics.

### Attachments

Minecraft Villagers

### Feature Request tracker rule checks (please read carefully)

- [X] I have checked NorthWestTrees Gaming YouTube Channel <a href='https://www.youtube.com/@NorthWestTreesGaming' target='_blank'> MCreator Playlists</a> and it has not been made yet.
- [X] I have checked MCE <a href='https://github.com/orgs/MCreator-Examples/projects/7/views/1?groupedBy%5BcolumnId%5D=Status' target='_blank'>Organaization Projects</a> and the idea has not been suggested yet.</a>

**Comment by Goldorion** [comment]
(Update: Simply using the new villager profession mod element will make a better job)
